name: Build and test lib
on: 'push'
defaults:
  run:
    working-directory: packages/lib
jobs:
  lib-workflow:
    runs-on: ubuntu-latest
    name: 'Lib workflow'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: ./.github/workflows/actions/setup-node
      - name: 'Build and test'
        uses: ./.github/workflows/actions/lib-build-and-test
